import Head from "next/head";
import Image from "next/image";
import Hero from "../components/Hero";
import Instagram from "../components/instragram";
import Slider from "../components/Slider";
import { SliderData } from "../components/SliderData";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Adit Malla</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero myName="Adit Malla" myProfession="I develop web applications." />
      <Slider slides={SliderData} />
      <Instagram />
    </div>
  );
}
